import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Navbar } from "@/components/Navbar";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { format } from "date-fns";
import { es } from "date-fns/locale";
import {
  ArrowDown,
  ArrowLeft,
  ArrowUp,
  CheckCircle2,
  Copy,
  Download,
  ExternalLink,
  Instagram,
  Link2,
  ListOrdered,
  Plus,
  RotateCcw,
  X,
} from "lucide-react";
import { parseDateValue } from "@/lib/date";
import {
  createArticleStoryPngBlob,
  extractArticleConcepts,
  getArticleStoryCaption,
  getArticleStoryDateLabel,
  getArticleStorySummary,
  getArticleStoryUrl,
} from "@/lib/article-story";

interface Article {
  id: string;
  slug: string;
  headline: string;
  summary: string | null;
  body_markdown: string | null;
  status: string;
  created_at: string;
  published_at: string | null;
  image_url: string | null;
  instagram_selected: boolean;
  instagram_published: boolean;
  instagram_order: number | null;
}

interface StoryDraft {
  headline: string;
  summary: string;
  conceptsText: string;
}

interface GeneratedStory {
  url: string;
  fileName: string;
  usedArticleImage: boolean;
}

type GeneratedStories = Record<string, GeneratedStory>;
type GeneratingStoryIds = Record<string, boolean>;

function sortInstagramArticles(articles: Article[]) {
  return [...articles].sort((left, right) => {
    const leftOrder = left.instagram_order ?? Number.MAX_SAFE_INTEGER;
    const rightOrder = right.instagram_order ?? Number.MAX_SAFE_INTEGER;

    if (leftOrder !== rightOrder) return leftOrder - rightOrder;

    const leftTime = parseDateValue(left.published_at || left.created_at).getTime();
    const rightTime = parseDateValue(right.published_at || right.created_at).getTime();
    return rightTime - leftTime;
  });
}

function getDefaultStoryDraft(article: Article): StoryDraft {
  return {
    headline: article.headline,
    summary: getArticleStorySummary(article),
    conceptsText: extractArticleConcepts(article).join(", "),
  };
}

function parseStoryConcepts(conceptsText: string) {
  return Array.from(
    new Set(
      conceptsText
        .split(/[,;\n]/)
        .map((concept) => concept.trim())
        .filter(Boolean),
    ),
  ).slice(0, 8);
}

function getDraftCaption(article: Article, draft: StoryDraft) {
  const concepts = parseStoryConcepts(draft.conceptsText);

  return getArticleStoryCaption(
    {
      ...article,
      headline: draft.headline.trim() || article.headline,
      summary: draft.summary,
    },
    concepts.length > 0 ? concepts : extractArticleConcepts(article),
  );
}

async function copyToClipboard(text: string) {
  if (!text) return;

  if (typeof navigator !== "undefined" && navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(text);
    return;
  }

  if (typeof document === "undefined") return;

  const textArea = document.createElement("textarea");
  textArea.value = text;
  textArea.setAttribute("readonly", "");
  textArea.style.position = "absolute";
  textArea.style.left = "-9999px";
  document.body.appendChild(textArea);
  textArea.select();
  document.execCommand("copy");
  document.body.removeChild(textArea);
}

export default function AdminNoticiasInstagram() {
  const { toast } = useToast();
  const [articles, setArticles] = useState<Article[]>([]);
  const [articleToAddId, setArticleToAddId] = useState("");
  const [storyDrafts, setStoryDrafts] = useState<Record<string, StoryDraft>>({});
  const [generatedStories, setGeneratedStories] = useState<GeneratedStories>({});
  const [generatingStoryIds, setGeneratingStoryIds] = useState<GeneratingStoryIds>({});
  const generatedStoriesRef = useRef<GeneratedStories>({});
  const autoGeneratedArticleIdsRef = useRef<Set<string>>(new Set());

  const fetchArticles = useCallback(async () => {
    const { data, error } = await supabase
      .from("articles")
      .select("id, slug, headline, summary, body_markdown, status, created_at, published_at, image_url, instagram_selected, instagram_published, instagram_order")
      .eq("status", "published")
      .order("published_at", { ascending: false });

    if (error) {
      toast({
        title: "No se pudo cargar Instagram",
        description: error.message,
        variant: "destructive",
      });
      return;
    }

    setArticles((data ?? []) as Article[]);
  }, [toast]);

  useEffect(() => {
    void fetchArticles();
  }, [fetchArticles]);

  useEffect(() => {
    generatedStoriesRef.current = generatedStories;
  }, [generatedStories]);

  useEffect(() => {
    return () => {
      Object.values(generatedStoriesRef.current).forEach((story) => URL.revokeObjectURL(story.url));
    };
  }, []);

  const availableArticles = useMemo(
    () =>
      [...articles]
        .filter((article) => !article.instagram_selected)
        .sort((left, right) => {
          const leftTime = parseDateValue(left.published_at || left.created_at).getTime();
          const rightTime = parseDateValue(right.published_at || right.created_at).getTime();
          return rightTime - leftTime;
        }),
    [articles],
  );

  const instagramPendingArticles = useMemo(
    () => sortInstagramArticles(articles.filter((article) => article.instagram_selected && !article.instagram_published)),
    [articles],
  );

  const instagramPublishedArticles = useMemo(
    () => sortInstagramArticles(articles.filter((article) => article.instagram_selected && article.instagram_published)),
    [articles],
  );

  useEffect(() => {
    const nextArticleToAddId = availableArticles.find((article) => article.id === articleToAddId)?.id
      ?? availableArticles[0]?.id
      ?? "";
    if (nextArticleToAddId !== articleToAddId) {
      setArticleToAddId(nextArticleToAddId);
    }
  }, [availableArticles, articleToAddId]);

  useEffect(() => {
    const pendingIds = new Set(instagramPendingArticles.map((article) => article.id));
    autoGeneratedArticleIdsRef.current = new Set(
      [...autoGeneratedArticleIdsRef.current].filter((articleId) => pendingIds.has(articleId)),
    );

    setStoryDrafts((previousDrafts) => {
      let changed = false;
      const nextDrafts: Record<string, StoryDraft> = {};

      for (const article of instagramPendingArticles) {
        const draft = previousDrafts[article.id];
        nextDrafts[article.id] = draft ?? getDefaultStoryDraft(article);
        if (!draft) changed = true;
      }

      if (Object.keys(previousDrafts).some((articleId) => !pendingIds.has(articleId))) {
        changed = true;
      }

      return changed ? nextDrafts : previousDrafts;
    });

    setGeneratedStories((previousStories) => {
      let changed = false;
      const nextStories: GeneratedStories = {};

      for (const [articleId, story] of Object.entries(previousStories)) {
        if (pendingIds.has(articleId)) {
          nextStories[articleId] = story;
          continue;
        }

        URL.revokeObjectURL(story.url);
        changed = true;
      }

      return changed ? nextStories : previousStories;
    });

    setGeneratingStoryIds((previousIds) => {
      let changed = false;
      const nextIds: GeneratingStoryIds = {};

      for (const [articleId, isGenerating] of Object.entries(previousIds)) {
        if (pendingIds.has(articleId)) {
          nextIds[articleId] = isGenerating;
          continue;
        }

        changed = true;
      }

      return changed ? nextIds : previousIds;
    });
  }, [instagramPendingArticles]);

  const generateStoryImage = useCallback(
    async (
      article: Article,
      draft: StoryDraft,
      options?: {
        silent?: boolean;
      },
    ) => {
      const concepts = parseStoryConcepts(draft.conceptsText);
      const nextHeadline = draft.headline.trim() || article.headline;
      const nextSummary = draft.summary.trim();

      setGeneratingStoryIds((previousIds) => ({
        ...previousIds,
        [article.id]: true,
      }));

      try {
        const { blob, usedArticleImage } = await createArticleStoryPngBlob({
          headline: nextHeadline,
          summary: nextSummary,
          concepts: concepts.length > 0 ? concepts : extractArticleConcepts(article),
          dateLabel: getArticleStoryDateLabel(article),
          url: getArticleStoryUrl(article.slug),
          imageUrl: article.image_url,
        });

        const objectUrl = URL.createObjectURL(blob);
        setGeneratedStories((previousStories) => {
          const previousStory = previousStories[article.id];
          if (previousStory?.url && previousStory.url !== objectUrl) {
            URL.revokeObjectURL(previousStory.url);
          }

          return {
            ...previousStories,
            [article.id]: {
              url: objectUrl,
              fileName: `${article.slug}-story-instagram.png`,
              usedArticleImage,
            },
          };
        });

        if (!options?.silent) {
          toast({
            title: "Imagen lista",
            description: usedArticleImage
              ? "La story quedó actualizada para descargar."
              : "La story quedó con fondo editorial porque la imagen externa no permitió exportarla.",
          });
        }
      } catch (error) {
        toast({
          title: "No se pudo crear la imagen",
          description: error instanceof Error ? error.message : "Intenta nuevamente.",
          variant: "destructive",
        });
      } finally {
        setGeneratingStoryIds((previousIds) => ({
          ...previousIds,
          [article.id]: false,
        }));
      }
    },
    [toast],
  );

  useEffect(() => {
    for (const article of instagramPendingArticles) {
      if (
        generatedStories[article.id]
        || generatingStoryIds[article.id]
        || autoGeneratedArticleIdsRef.current.has(article.id)
      ) {
        continue;
      }

      const draft = storyDrafts[article.id] ?? getDefaultStoryDraft(article);
      autoGeneratedArticleIdsRef.current.add(article.id);
      void generateStoryImage(article, draft, { silent: true });
    }
  }, [generateStoryImage, generatedStories, generatingStoryIds, instagramPendingArticles, storyDrafts]);

  const handleStoryDraftChange = useCallback((article: Article, field: keyof StoryDraft, value: string) => {
    setStoryDrafts((previousDrafts) => ({
      ...previousDrafts,
      [article.id]: {
        ...(previousDrafts[article.id] ?? getDefaultStoryDraft(article)),
        [field]: value,
      },
    }));
  }, []);

  const resequenceInstagramOrders = async (queue: Article[]) => {
    if (queue.length === 0) return true;

    const results = await Promise.all(
      queue.map((article, index) =>
        supabase
          .from("articles")
          .update({ instagram_order: index + 1 })
          .eq("id", article.id),
      ),
    );

    const failedResult = results.find((result) => result.error);
    if (failedResult?.error) {
      toast({
        title: "No se pudo reordenar Instagram",
        description: failedResult.error.message,
        variant: "destructive",
      });
      return false;
    }

    return true;
  };

  const handleAddToInstagram = async () => {
    const article = availableArticles.find((entry) => entry.id === articleToAddId);
    if (!article) return;

    const nextOrder = instagramPendingArticles.length + 1;
    const { error } = await supabase
      .from("articles")
      .update({
        instagram_selected: true,
        instagram_published: false,
        instagram_order: nextOrder,
      })
      .eq("id", article.id);

    if (error) {
      toast({
        title: "No se pudo agregar a Instagram",
        description: error.message,
        variant: "destructive",
      });
      return;
    }

    toast({
      title: "Agregada a Instagram",
      description: "La noticia quedó lista para descargar como story.",
    });
    void fetchArticles();
  };

  const handleToggleInstagramSelection = async (article: Article) => {
    const sourceQueue = sortInstagramArticles(
      (article.instagram_published ? instagramPublishedArticles : instagramPendingArticles).filter(
        (entry) => entry.id !== article.id,
      ),
    );

    const [updateResult, resequenceOk] = await Promise.all([
      supabase
        .from("articles")
        .update({
          instagram_selected: false,
          instagram_published: false,
          instagram_order: null,
        })
        .eq("id", article.id),
      resequenceInstagramOrders(sourceQueue),
    ]);

    if (updateResult.error) {
      toast({
        title: "No se pudo quitar de Instagram",
        description: updateResult.error.message,
        variant: "destructive",
      });
      return;
    }

    if (!resequenceOk) return;

    toast({
      title: "Quitada de Instagram",
      description: "La noticia salió de la cola de publicaciones.",
    });
    void fetchArticles();
  };

  const handleSetInstagramPublished = async (article: Article, nextPublished: boolean) => {
    const sourceQueue = sortInstagramArticles(
      (article.instagram_published ? instagramPublishedArticles : instagramPendingArticles).filter(
        (entry) => entry.id !== article.id,
      ),
    );
    const destinationQueue = nextPublished ? instagramPublishedArticles : instagramPendingArticles;
    const nextOrder = destinationQueue.length + 1;

    const [updateResult, resequenceOk] = await Promise.all([
      supabase
        .from("articles")
        .update({
          instagram_selected: true,
          instagram_published: nextPublished,
          instagram_order: nextOrder,
        })
        .eq("id", article.id),
      resequenceInstagramOrders(sourceQueue),
    ]);

    if (updateResult.error) {
      toast({
        title: "No se pudo mover la noticia",
        description: updateResult.error.message,
        variant: "destructive",
      });
      return;
    }

    if (!resequenceOk) return;

    toast({
      title: nextPublished ? "Marcada como publicada" : "Marcada como pendiente",
      description: nextPublished
        ? "La noticia pasó al historial de Instagram."
        : "La noticia volvió a las stories listas para descargar.",
    });
    void fetchArticles();
  };

  const handleMoveInstagramArticle = async (article: Article, direction: -1 | 1) => {
    const queue = article.instagram_published ? instagramPublishedArticles : instagramPendingArticles;
    const currentIndex = queue.findIndex((entry) => entry.id === article.id);
    const nextIndex = currentIndex + direction;

    if (currentIndex === -1 || nextIndex < 0 || nextIndex >= queue.length) return;

    const nextQueue = [...queue];
    const [movedArticle] = nextQueue.splice(currentIndex, 1);
    nextQueue.splice(nextIndex, 0, movedArticle);

    const resequenceOk = await resequenceInstagramOrders(nextQueue);
    if (!resequenceOk) return;

    void fetchArticles();
  };

  const resetStoryDraft = (article: Article) => {
    const nextDraft = getDefaultStoryDraft(article);
    setStoryDrafts((previousDrafts) => ({
      ...previousDrafts,
      [article.id]: nextDraft,
    }));
    void generateStoryImage(article, nextDraft, { silent: true });
  };

  const handleCopyStoryLink = async (article: Article) => {
    try {
      await copyToClipboard(getArticleStoryUrl(article.slug));
      toast({ title: "Link copiado", description: "El link público de la noticia quedó listo para pegar." });
    } catch (error) {
      toast({
        title: "No se pudo copiar el link",
        description: error instanceof Error ? error.message : "Intenta de nuevo en unos segundos.",
        variant: "destructive",
      });
    }
  };

  const handleCopyStoryCaption = async (article: Article, draft: StoryDraft) => {
    try {
      await copyToClipboard(getDraftCaption(article, draft));
      toast({ title: "Caption copiado", description: "Copié un texto base con hashtags y link." });
    } catch (error) {
      toast({
        title: "No se pudo copiar el caption",
        description: error instanceof Error ? error.message : "Intenta de nuevo en unos segundos.",
        variant: "destructive",
      });
    }
  };

  const handleDownloadStory = (story: GeneratedStory | undefined) => {
    if (!story) return;

    const link = document.createElement("a");
    link.href = story.url;
    link.download = story.fileName;
    link.click();
  };

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <div className="container mx-auto px-4 py-8">
        <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
          <div>
            <Link to="/admin/noticias" className="mb-3 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground">
              <ArrowLeft className="h-4 w-4" />
              Volver a noticias
            </Link>
            <h1 className="text-3xl font-display font-bold">Instagram de noticias</h1>
            <p className="mt-1 max-w-3xl text-sm text-muted-foreground">
              Elegí noticias, descargá la story y marcala como publicada desde un solo lugar.
            </p>
          </div>
          <div className="flex flex-wrap gap-2">
            <Badge variant="outline" className="border-primary/25 bg-primary/10 text-primary">
              Listas: {instagramPendingArticles.length}
            </Badge>
            <Badge variant="outline" className="border-muted-foreground/20 bg-muted/50 text-muted-foreground">
              Publicadas: {instagramPublishedArticles.length}
            </Badge>
          </div>
        </div>

        <div className="space-y-5">
          <section className="rounded-lg border border-border bg-card/90 p-5 shadow-[var(--shadow-card)]">
            <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-end">
              <div>
                <div className="mb-3 inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-3 py-1 text-xs font-semibold uppercase tracking-[0.18em] text-primary">
                  <Plus className="h-3.5 w-3.5" />
                  Agregar
                </div>
                <Label>Noticia publicada</Label>
                {availableArticles.length > 0 ? (
                  <Select value={articleToAddId} onValueChange={setArticleToAddId}>
                    <SelectTrigger className="mt-2">
                      <SelectValue placeholder="Selecciona una noticia" />
                    </SelectTrigger>
                    <SelectContent>
                      {availableArticles.map((article) => (
                        <SelectItem key={article.id} value={article.id}>
                          {article.headline}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                ) : (
                  <div className="mt-2 rounded-lg border border-dashed border-border px-4 py-3 text-sm text-muted-foreground">
                    No hay más noticias publicadas disponibles para agregar a Instagram.
                  </div>
                )}
              </div>
              <Button onClick={() => void handleAddToInstagram()} disabled={!articleToAddId || availableArticles.length === 0}>
                <Instagram className="mr-2 h-4 w-4" />
                Agregar a stories
              </Button>
            </div>
          </section>

          <section className="rounded-lg border border-border bg-card/90 p-5 shadow-[var(--shadow-card)]">
            <div className="mb-4 flex flex-wrap items-start justify-between gap-3">
              <div>
                <div className="inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-3 py-1 text-xs font-semibold uppercase tracking-[0.18em] text-primary">
                  <ListOrdered className="h-3.5 w-3.5" />
                  Stories
                </div>
                <h2 className="mt-3 text-xl font-display font-bold">Listas para descargar</h2>
                <p className="mt-1 text-sm text-muted-foreground">
                  Las pendientes ya aparecen con preview, texto editable y descarga directa.
                </p>
              </div>
              <Badge variant="outline">{instagramPendingArticles.length}</Badge>
            </div>

            <div className="grid gap-4">
              {instagramPendingArticles.map((article, index) => {
                const draft = storyDrafts[article.id] ?? getDefaultStoryDraft(article);
                const story = generatedStories[article.id];
                const isGenerating = Boolean(generatingStoryIds[article.id]);
                const storyLink = getArticleStoryUrl(article.slug);

                return (
                  <article key={article.id} className="rounded-lg border border-border bg-background/50 p-4">
                    <div className="mb-4 flex flex-wrap items-start justify-between gap-3">
                      <div className="min-w-0">
                        <div className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
                          <Badge variant="outline">Orden {index + 1}</Badge>
                          <Badge
                            variant="outline"
                            className={
                              story
                                ? story.usedArticleImage
                                  ? "border-primary/25 bg-primary/10 text-primary"
                                  : "border-muted-foreground/20 bg-muted/50"
                                : "border-muted-foreground/20 bg-muted/50"
                            }
                          >
                            {story ? (story.usedArticleImage ? "Imagen original" : "Fondo editorial") : "Generando"}
                          </Badge>
                          <span>1080 x 1920</span>
                          {article.published_at && (
                            <span>{format(parseDateValue(article.published_at), "d MMM yyyy", { locale: es })}</span>
                          )}
                        </div>
                        <h3 className="mt-2 line-clamp-2 text-lg font-display font-bold">{article.headline}</h3>
                      </div>

                      <div className="flex shrink-0 items-center gap-1">
                        <Button
                          size="icon"
                          variant="ghost"
                          onClick={() => void handleMoveInstagramArticle(article, -1)}
                          disabled={index === 0}
                          title="Subir"
                        >
                          <ArrowUp className="h-4 w-4" />
                        </Button>
                        <Button
                          size="icon"
                          variant="ghost"
                          onClick={() => void handleMoveInstagramArticle(article, 1)}
                          disabled={index === instagramPendingArticles.length - 1}
                          title="Bajar"
                        >
                          <ArrowDown className="h-4 w-4" />
                        </Button>
                        <Button
                          size="icon"
                          variant="ghost"
                          onClick={() => void handleToggleInstagramSelection(article)}
                          title="Quitar"
                        >
                          <X className="h-4 w-4" />
                        </Button>
                      </div>
                    </div>

                    <div className="grid gap-5 xl:grid-cols-[220px_minmax(0,1fr)] 2xl:grid-cols-[260px_minmax(0,1fr)]">
                      <div className="mx-auto w-full max-w-[220px] 2xl:max-w-[260px]">
                        <div className="relative aspect-[9/16] overflow-hidden rounded-lg border border-white/10 bg-[#09070d] shadow-[0_18px_40px_rgba(0,0,0,0.32)]">
                          {story ? (
                            <img
                              src={story.url}
                              alt={`Story generada de ${article.headline}`}
                              className="h-full w-full object-cover"
                            />
                          ) : (
                            <div className="flex h-full items-center justify-center px-5 text-center text-sm text-white/70">
                              {isGenerating ? "Creando imagen..." : "Preparando preview..."}
                            </div>
                          )}
                        </div>
                        <p className="mt-2 truncate text-center text-xs text-muted-foreground">
                          {story ? story.fileName : "Se genera sola al cargar."}
                        </p>
                      </div>

                      <div className="min-w-0 space-y-3">
                        <div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]">
                          <div>
                            <Label>Titular</Label>
                            <Textarea
                              className="mt-2 min-h-[88px]"
                              rows={3}
                              value={draft.headline}
                              onChange={(event) => handleStoryDraftChange(article, "headline", event.target.value)}
                              placeholder="Titular para la story"
                            />
                          </div>

                          <div>
                            <Label>Resumen</Label>
                            <Textarea
                              className="mt-2 min-h-[88px]"
                              rows={3}
                              value={draft.summary}
                              onChange={(event) => handleStoryDraftChange(article, "summary", event.target.value)}
                              placeholder="Resumen breve"
                            />
                          </div>
                        </div>

                        <div>
                          <Label>Conceptos</Label>
                          <Input
                            className="mt-2"
                            value={draft.conceptsText}
                            onChange={(event) => handleStoryDraftChange(article, "conceptsText", event.target.value)}
                            placeholder="Ej: WSOP, Montevideo, Main Event"
                          />
                        </div>

                        <div className="flex flex-wrap gap-2 pt-1">
                          <Button onClick={() => handleDownloadStory(story)} disabled={!story || isGenerating}>
                            <Download className="mr-2 h-4 w-4" />
                            Descargar PNG
                          </Button>
                          <Button
                            variant="outline"
                            onClick={() => void generateStoryImage(article, draft)}
                            disabled={isGenerating}
                          >
                            <Instagram className="mr-2 h-4 w-4" />
                            {isGenerating ? "Actualizando..." : "Actualizar"}
                          </Button>
                          <Button variant="outline" onClick={() => void handleCopyStoryCaption(article, draft)}>
                            <Copy className="mr-2 h-4 w-4" />
                            Caption
                          </Button>
                          <Button variant="outline" onClick={() => void handleCopyStoryLink(article)}>
                            <Link2 className="mr-2 h-4 w-4" />
                            Link
                          </Button>
                          <Button variant="outline" onClick={() => void handleSetInstagramPublished(article, true)}>
                            <CheckCircle2 className="mr-2 h-4 w-4" />
                            Publicada
                          </Button>
                          <Button variant="ghost" onClick={() => resetStoryDraft(article)}>
                            <RotateCcw className="mr-2 h-4 w-4" />
                            Restaurar
                          </Button>
                          <Button variant="ghost" asChild>
                            <a href={storyLink} target="_blank" rel="noopener noreferrer">
                              <ExternalLink className="mr-2 h-4 w-4" />
                              Ver noticia
                            </a>
                          </Button>
                        </div>
                      </div>
                    </div>
                  </article>
                );
              })}

              {instagramPendingArticles.length === 0 && (
                <div className="rounded-lg border border-dashed border-border px-4 py-10 text-center text-sm text-muted-foreground">
                  No hay noticias pendientes para Instagram.
                </div>
              )}
            </div>
          </section>

          <section className="rounded-lg border border-border bg-card/90 p-5 shadow-[var(--shadow-card)]">
            <div className="mb-4 flex items-start justify-between gap-3">
              <div>
                <div className="inline-flex items-center gap-2 rounded-full border border-muted-foreground/20 bg-muted/40 px-3 py-1 text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">
                  <CheckCircle2 className="h-3.5 w-3.5" />
                  Historial
                </div>
                <h2 className="mt-3 text-xl font-display font-bold">Ya publicadas</h2>
              </div>
              <Badge variant="outline">{instagramPublishedArticles.length}</Badge>
            </div>

            <div className="grid gap-3 xl:grid-cols-2">
              {instagramPublishedArticles.map((article, index) => (
                <div key={article.id} className="rounded-lg border border-border bg-background/50 px-3 py-3">
                  <div className="flex items-start justify-between gap-3">
                    <div className="min-w-0">
                      <p className="font-medium text-foreground line-clamp-2">{article.headline}</p>
                      <div className="mt-2 flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
                        <Badge variant="outline">Orden {index + 1}</Badge>
                        {article.published_at && (
                          <span>{format(parseDateValue(article.published_at), "d MMM yyyy", { locale: es })}</span>
                        )}
                      </div>
                    </div>
                    <div className="flex shrink-0 items-center gap-1">
                      <Button
                        size="icon"
                        variant="ghost"
                        onClick={() => void handleMoveInstagramArticle(article, -1)}
                        disabled={index === 0}
                        title="Subir"
                      >
                        <ArrowUp className="h-4 w-4" />
                      </Button>
                      <Button
                        size="icon"
                        variant="ghost"
                        onClick={() => void handleMoveInstagramArticle(article, 1)}
                        disabled={index === instagramPublishedArticles.length - 1}
                        title="Bajar"
                      >
                        <ArrowDown className="h-4 w-4" />
                      </Button>
                    </div>
                  </div>

                  <div className="mt-3 flex flex-wrap gap-2">
                    <Button size="sm" variant="outline" onClick={() => void handleSetInstagramPublished(article, false)}>
                      <RotateCcw className="mr-2 h-4 w-4" />
                      Volver a pendientes
                    </Button>
                    <Button size="sm" variant="ghost" onClick={() => void handleToggleInstagramSelection(article)}>
                      <X className="mr-2 h-4 w-4" />
                      Quitar
                    </Button>
                  </div>
                </div>
              ))}

              {instagramPublishedArticles.length === 0 && (
                <div className="rounded-lg border border-dashed border-border px-4 py-8 text-center text-sm text-muted-foreground xl:col-span-2">
                  Todavía no marcaste noticias como publicadas en Instagram.
                </div>
              )}
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}
